export const environment = {
    SUPABASE_URL : process.env.NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_KEY : process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    SUPABASE_ADMIN : process.env.NEXT_PUBLIC_SUPABASE_SERVICE_KEY
}